Server performance --requires testing
Irev-Dev/Lucy-Web pull request #14
Opened 2018-04-16 18:01 UTC by mrhut10

observational data

- zeit deployments looks like a decreased response times by 100 to 200 ms
- on local deployments more like a 500 to 600 ms decrease in response times
- and when under load will greatly reduce database calls

Testing still required by @Irev-Dev 
- do flashes still work where they are needed ???
- does the GET /reg url still work???

2018-04-16 18:03 UTC, mrhut10 commented on package.json
> +    "build-js": "parcel build server/client/client.js --out-dir server/client/dist  --public-url ./ --log-level 1",
this reduces the logs being filled with build statements, will only log errors now

2018-04-16 18:03 UTC, mrhut10 commented on package.json
> +    "parcel-bundler": "^1.7.1"
updated parcel version to allow for the --log-level feature

2018-04-16 18:04 UTC, mrhut10 commented on server/controllers/userController.js
>  function CachedCountDown() {
this function could likely be completely removed or at least moved into a way where we write a generalised caching function within the caching library.

2018-04-16 18:05 UTC, mrhut10 commented on server/server.js
> +  responseCache(20 * 1000), // cache body data for 20 seconds
these caching times are arbitory for when i was testing it. please review these times @Irev-Dev

2018-04-16 18:07 UTC, mrhut10 reviewed
@Irev-Dev 
- does flashes still work?
- does GET /reg url still work
- review caching times for routes
- have a fun time

2018-04-20 21:05 UTC, Irev-Dev requested changes
flashes are in-fact now broken, they get bundled up as part of the cache eg when you sign up you are given a verify link that when navigated to gives you a success flash, but if you navigate to it for a second time you should get an info flash saying that you have already verified, but now with these changes you keep getting the success flash until the cache refreshes.

2018-04-21 05:06 UTC, mrhut10 commented
OK I should be able to fix that fairly easily if you haven't already, I'll close the request now and resubmit a fix. 
:)
Kind regards

2018-04-21 05:06 UTC, closed without merging